# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd2194abf7c9a4233a4b4ba4f24b9f55853d947b5490149080cd89cbcbed90a506f5b93aa1aeb8a0628147ea2d9413be682a98c19f2a162194471aa4151485c

test:
  secret_key_base: fdee4b15128fef5bf79b02e54a5d7c1a96c42cdde5d99f593699a436771d6fe2d2a7608b21c582a990d1d7c3dbf0f2bccacfa4f3bac860c48fd0a627ae9d73b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
